---
all:
  children:
    bootc_systems:
      hosts:
        # Add deployed bootc hosts here
        # example:
        #   bootc-host-01:
        #     ansible_host: 192.168.1.100
        #     ansible_user: uryu
